# Generated by Django 3.2.13 on 2024-12-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='vm',
            name='ssh_key',
            field=models.TextField(help_text='SSH key for secure VM access', null=True),
        ),
    ]
